package xyz.fullstacks.demo.awsdev.model;

import org.springframework.data.annotation.Id;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonIgnore;

import lombok.Data;

@Data
@DynamoDBTable(tableName = "User")
public class User {

	@Id
	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
    @JsonIgnore
	private String id;
	
	@DynamoDBAttribute(attributeName = "firstName")
	private String firstName;
	
	@DynamoDBAttribute(attributeName = "lastName")
	private String lastName;

//	public User() {
//		// Default constructor is required by AWS DynamoDB SDK
//	}
//
//	public User(String firstName, String lastName) {
//		this.firstName = firstName;
//		this.lastName = lastName;
//	}
//
//	@DynamoDBHashKey
//	@DynamoDBAutoGeneratedKey
//	public String getId() {
//		return id;
//	}
//
//	@DynamoDBAttribute
//	public String getFirstName() {
//		return firstName;
//	}
//
//	@DynamoDBAttribute
//	public String getLastName() {
//		return lastName;
//	}
}